server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: 1234

  ## thymeleaf模板设置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: utf-8
    servlet.content-type: text/html
    cache: false

  ## 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB